version: '3.5'

networks:
  map-my-world:
    external: false

services:

  pg-map-my-world-localhost:
    image: "postgres:14.2"
    container_name: pg-map-my-world-localhost
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=Test
      - POSTGRES_PASSWORD=Test
      - POSTGRES_DB=map-my-world
      - DEBUG=True
    restart: always
    networks:
      - map-my-world

  redis-map-my-world-localhost:
    image: "redis:latest"
    container_name: redis-map-my-world-localhost
    ports:
      - 6379:6379
    networks:
      - map-my-world